// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ0GLGbbzryrps8w-XH-Agmo1olAXu3jM',
    appId: '1:640131188082:web:687c1192f889de154b89eb',
    messagingSenderId: '640131188082',
    projectId: 'messages-board-18caa',
    authDomain: 'messages-board-18caa.firebaseapp.com',
    storageBucket: 'messages-board-18caa.firebasestorage.app',
    measurementId: 'G-BYQRCEPQ8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgL6_F2d8acPsR2uiLQ1v4H8Q-EDHrOMM',
    appId: '1:640131188082:android:414d837eeea1ee5e4b89eb',
    messagingSenderId: '640131188082',
    projectId: 'messages-board-18caa',
    storageBucket: 'messages-board-18caa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEb_FhcgZiR-XGT7PIplOmGdFgcAiWpRs',
    appId: '1:640131188082:ios:03315486bcb9089a4b89eb',
    messagingSenderId: '640131188082',
    projectId: 'messages-board-18caa',
    storageBucket: 'messages-board-18caa.firebasestorage.app',
    iosBundleId: 'com.example.messagesBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEb_FhcgZiR-XGT7PIplOmGdFgcAiWpRs',
    appId: '1:640131188082:ios:03315486bcb9089a4b89eb',
    messagingSenderId: '640131188082',
    projectId: 'messages-board-18caa',
    storageBucket: 'messages-board-18caa.firebasestorage.app',
    iosBundleId: 'com.example.messagesBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ0GLGbbzryrps8w-XH-Agmo1olAXu3jM',
    appId: '1:640131188082:web:81ec48cb5a5e29a94b89eb',
    messagingSenderId: '640131188082',
    projectId: 'messages-board-18caa',
    authDomain: 'messages-board-18caa.firebaseapp.com',
    storageBucket: 'messages-board-18caa.firebasestorage.app',
    measurementId: 'G-XBTNFMK031',
  );
}
